version: '3.0'
services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_DB=messageDB
          - POSTGRES_USER=milpe
          - POSTGRES_PASSWORD=123456
        ports:
          - "5432:5432"
        volumes:
          - C:/Users/lucas/source/repos/Volumes:/var/lib/postgresql/data

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        ports:
          - "5434:1433"
        volumes:
          - C:/Users/lucas/source/repos/VolumesSQLServer:/var/opt/mssql/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - "discovery.type=single-node"
        ports:
          - 9200:9200

    messaginserivce:

volumes:
  pgdata:
      
  
      
  #kibana:
  #  image: docker.elastic.co/kibana/kibana:7.11.0
  #  environment:
  #    - ELASTICSEARCH_HOSTS=http://es-container:9200
  #  depends_on:
  #    - elasticsearch
  #  ports:
  #    - 5601:5601
      
  #zookeeper:
  #  image: confluentinc/cp-zookeeper:latest
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #    ZOOKEEPER_TICK_TIME: 2000
  #  ports:
  #    - 22181:2181
  
  #kafka:
  #  image: confluentinc/cp-kafka:latest
  #  depends_on:
  #    - zookeeper
  #  ports:
  #    - 29092:29092
  #  environment:
  #    KAFKA_BROKER_ID: 1
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1